[package]
name = "devices"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[features]
amd-sev = []

[dependencies]
bitflags = "1.2.0"
libc = ">=0.2.39"
lru = "0.6.3"

arch = { path = "../arch" }
logger = { path = "../logger" }
vm-memory = { git = "https://github.com/rust-vmm/vm-memory", features = ["backend-mmap"] }
utils = { path = "../utils" }
polly = { path = "../polly" }
virtio_gen = { path = "../virtio_gen" }

[target.'cfg(target_os = "macos")'.dependencies]
hvf = { path = "../hvf" }
