[package]
name = "hvf"
version = "0.1.0"
authors = ["Sergio Lopez <slp@sinrega.org>"]
edition = "2021"

[dependencies]
crossbeam-channel = ">=0.5.15"
libloading = "0.8"
log = "0.4.0"
env_logger = "0.9.0"

arch = { path = "../arch" }
